
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Oct 26 2025 12:01:04 IST (Oct 26 2025 06:31:04 UTC)

// Verification Directory fv/XOR_PUF_Top_With_Pads 

module ArbiterCell(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  CDN_flop response_bit_reg(.clk (path_b_sig), .d (path_b_sig), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (response_bit));
endmodule

module ArbiterPUF_Chain(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_1(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  CDN_flop response_bit_reg(.clk (path_b_sig), .d (path_b_sig), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (response_bit));
endmodule

module ComplexPUF_Chain(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_1 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterPUF_Chain_15(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_7(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  CDN_flop response_bit_reg(.clk (path_b_sig), .d (path_b_sig), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (response_bit));
endmodule

module ComplexPUF_Chain_3_17(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_7 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterPUF_Chain_14(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ComplexPUF_Chain_16(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_1 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterPUF_Chain_13(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ComplexPUF_Chain_3(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_7 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module XOR_PUF(Trigger, Challenge, FinalResponse);
  input Trigger;
  input [7:0] Challenge;
  output FinalResponse;
  wire Trigger;
  wire [7:0] Challenge;
  wire FinalResponse;
  wire [7:0] puf_bits;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36;
  ArbiterPUF_Chain puf1(Trigger, 8'b0, puf_bits[0]);
  ComplexPUF_Chain puf2(Trigger, 8'b0, 1'b0, puf_bits[1]);
  ArbiterPUF_Chain_15 puf3(Trigger, 8'b0, puf_bits[2]);
  ComplexPUF_Chain_3_17 puf4(Trigger, 8'b0, 1'b1, puf_bits[3]);
  ArbiterPUF_Chain_14 puf5(Trigger, 8'b0, puf_bits[4]);
  ComplexPUF_Chain_16 puf6(Trigger, 8'b0, 1'b0, puf_bits[5]);
  ArbiterPUF_Chain_13 puf7(Trigger, 8'b0, puf_bits[6]);
  ComplexPUF_Chain_3 puf8(Trigger, 8'b0, 1'b1, puf_bits[7]);
  or g12 (n_23, wc, n_20);
  not gc (wc, n_19);
  or g13 (n_24, n_19, wc0);
  not gc0 (wc0, n_20);
  nand g14 (FinalResponse, n_23, n_24);
  or g15 (n_25, wc1, n_16);
  not gc1 (wc1, n_15);
  or g16 (n_26, n_15, wc2);
  not gc2 (wc2, n_16);
  nand g17 (n_19, n_25, n_26);
  or g18 (n_27, wc3, n_18);
  not gc3 (wc3, n_17);
  or g19 (n_28, n_17, wc4);
  not gc4 (wc4, n_18);
  nand g20 (n_20, n_27, n_28);
  or g21 (n_29, wc5, puf_bits[7]);
  not gc5 (wc5, puf_bits[0]);
  or g22 (n_30, puf_bits[0], wc6);
  not gc6 (wc6, puf_bits[7]);
  nand g23 (n_15, n_29, n_30);
  or g24 (n_31, wc7, puf_bits[2]);
  not gc7 (wc7, puf_bits[4]);
  or g25 (n_32, puf_bits[4], wc8);
  not gc8 (wc8, puf_bits[2]);
  nand g26 (n_16, n_31, n_32);
  or g27 (n_33, wc9, puf_bits[3]);
  not gc9 (wc9, puf_bits[5]);
  or g28 (n_34, puf_bits[5], wc10);
  not gc10 (wc10, puf_bits[3]);
  nand g29 (n_17, n_33, n_34);
  or g30 (n_35, wc11, puf_bits[1]);
  not gc11 (wc11, puf_bits[6]);
  or g31 (n_36, puf_bits[6], wc12);
  not gc12 (wc12, puf_bits[1]);
  nand g32 (n_18, n_35, n_36);
endmodule

module XOR_PUF_Top(trigger, challenge, response);
  input trigger;
  input [7:0] challenge;
  output response;
  wire trigger;
  wire [7:0] challenge;
  wire response;
  XOR_PUF puf_inst(.Trigger (trigger), .Challenge (8'b0),
       .FinalResponse (response));
endmodule

module XOR_PUF_Top_With_Pads(i_trigger_pad, i_challenge_pad,
     o_response_pad);
  input i_trigger_pad;
  input [7:0] i_challenge_pad;
  output o_response_pad;
  wire i_trigger_pad;
  wire [7:0] i_challenge_pad;
  wire o_response_pad;
  wire response_int, trigger_int;
  XOR_PUF_Top core(.trigger (trigger_int), .challenge (8'b0), .response
       (response_int));
  pc3o05 pad_resp(.I (response_int), .PAD (o_response_pad));
  pc3d01 pad_trigger(.PAD (i_trigger_pad), .CIN (trigger_int));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
