
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Oct 26 2025 12:01:04 IST (Oct 26 2025 06:31:04 UTC)

// Verification Directory fv/XOR_PUF_Top_With_Pads 

module ArbiterCell(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_1(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_1 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_10(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain_15(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_10 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_7_12(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain_3_17(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_7_12 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_9(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain_14(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_9 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_1_11(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain_16(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_1_11 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_8(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain_13(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_8 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module ArbiterCell_7(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain_3(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  ArbiterCell_7 arbiter(.path_a_sig (1'b0), .path_b_sig (Trigger),
       .response_bit (Response));
endmodule

module XOR_PUF(Trigger, Challenge, FinalResponse);
  input Trigger;
  input [7:0] Challenge;
  output FinalResponse;
  wire Trigger;
  wire [7:0] Challenge;
  wire FinalResponse;
  wire [7:0] puf_bits;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  ArbiterPUF_Chain puf1(Trigger, 8'b0, puf_bits[0]);
  ComplexPUF_Chain puf2(Trigger, 8'b0, 1'b0, puf_bits[1]);
  ArbiterPUF_Chain_15 puf3(Trigger, 8'b0, puf_bits[2]);
  ComplexPUF_Chain_3_17 puf4(Trigger, 8'b0, 1'b1, puf_bits[3]);
  ArbiterPUF_Chain_14 puf5(Trigger, 8'b0, puf_bits[4]);
  ComplexPUF_Chain_16 puf6(Trigger, 8'b0, 1'b0, puf_bits[5]);
  ArbiterPUF_Chain_13 puf7(Trigger, 8'b0, puf_bits[6]);
  ComplexPUF_Chain_3 puf8(Trigger, 8'b0, 1'b1, puf_bits[7]);
  xr03d1 g72__2398(.A1 (n_5), .A2 (n_3), .A3 (n_4), .Z (FinalResponse));
  xr03d1 g73__5107(.A1 (n_2), .A2 (puf_bits[2]), .A3 (puf_bits[4]), .Z
       (n_5));
  xr02d1 g74__6260(.A1 (puf_bits[1]), .A2 (puf_bits[6]), .Z (n_4));
  aoim22d1 g75__4319(.A1 (n_0), .A2 (puf_bits[5]), .B1 (n_0), .B2
       (puf_bits[5]), .Z (n_3));
  aoim22d1 g76__8428(.A1 (n_1), .A2 (puf_bits[7]), .B1 (n_1), .B2
       (puf_bits[7]), .Z (n_2));
  inv0d0 g77(.I (puf_bits[0]), .ZN (n_1));
  inv0d0 g78(.I (puf_bits[3]), .ZN (n_0));
endmodule

module XOR_PUF_Top(trigger, challenge, response);
  input trigger;
  input [7:0] challenge;
  output response;
  wire trigger;
  wire [7:0] challenge;
  wire response;
  XOR_PUF puf_inst(.Trigger (trigger), .Challenge (8'b0),
       .FinalResponse (response));
endmodule

module XOR_PUF_Top_With_Pads(i_trigger_pad, i_challenge_pad,
     o_response_pad);
  input i_trigger_pad;
  input [7:0] i_challenge_pad;
  output o_response_pad;
  wire i_trigger_pad;
  wire [7:0] i_challenge_pad;
  wire o_response_pad;
  wire response_int, trigger_int;
  XOR_PUF_Top core(.trigger (trigger_int), .challenge (8'b0), .response
       (response_int));
  pc3o05 pad_resp(.I (response_int), .PAD (o_response_pad));
  pc3d01 pad_trigger(.PAD (i_trigger_pad), .CIN (trigger_int));
endmodule

