
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Oct 26 2025 12:01:05 IST (Oct 26 2025 06:31:05 UTC)

// Verification Directory fv/XOR_PUF_Top_With_Pads 

module ArbiterCell(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z;
  ArbiterCell arbiter(.path_a_sig (UNCONNECTED_HIER_Z), .path_b_sig
       (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_1(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z0;
  ArbiterCell_1 arbiter(.path_a_sig (UNCONNECTED_HIER_Z0), .path_b_sig
       (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_10(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain_15(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z1;
  ArbiterCell_10 arbiter(.path_a_sig (UNCONNECTED_HIER_Z1), .path_b_sig
       (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_7_12(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain_3_17(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z2;
  ArbiterCell_7_12 arbiter(.path_a_sig (UNCONNECTED_HIER_Z2),
       .path_b_sig (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_9(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain_14(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z3;
  ArbiterCell_9 arbiter(.path_a_sig (UNCONNECTED_HIER_Z3), .path_b_sig
       (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_1_11(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain_16(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z4;
  ArbiterCell_1_11 arbiter(.path_a_sig (UNCONNECTED_HIER_Z4),
       .path_b_sig (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_8(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ArbiterPUF_Chain_13(Trigger, Challenge, Response);
  input Trigger;
  input [7:0] Challenge;
  output Response;
  wire Trigger;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z5;
  ArbiterCell_8 arbiter(.path_a_sig (UNCONNECTED_HIER_Z5), .path_b_sig
       (Trigger), .response_bit (Response));
endmodule

module ArbiterCell_7(path_a_sig, path_b_sig, response_bit);
  input path_a_sig, path_b_sig;
  output response_bit;
  wire path_a_sig, path_b_sig;
  wire response_bit;
  dfnrq1 response_bit_reg(.CP (path_b_sig), .D (path_b_sig), .Q
       (response_bit));
endmodule

module ComplexPUF_Chain_3(Trigger, Challenge, Select, Response);
  input Trigger, Select;
  input [7:0] Challenge;
  output Response;
  wire Trigger, Select;
  wire [7:0] Challenge;
  wire Response;
  wire UNCONNECTED_HIER_Z6;
  ArbiterCell_7 arbiter(.path_a_sig (UNCONNECTED_HIER_Z6), .path_b_sig
       (Trigger), .response_bit (Response));
endmodule

module XOR_PUF(Trigger, Challenge, FinalResponse);
  input Trigger;
  input [7:0] Challenge;
  output FinalResponse;
  wire Trigger;
  wire [7:0] Challenge;
  wire FinalResponse;
  wire [7:0] puf_bits;
  wire UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14;
  wire UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22;
  wire UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z28,
       UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z30;
  wire UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z32,
       UNCONNECTED_HIER_Z33, UNCONNECTED_HIER_Z34,
       UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z38;
  wire UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z41, UNCONNECTED_HIER_Z42,
       UNCONNECTED_HIER_Z43, UNCONNECTED_HIER_Z44,
       UNCONNECTED_HIER_Z45, UNCONNECTED_HIER_Z46;
  wire UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z49, UNCONNECTED_HIER_Z50,
       UNCONNECTED_HIER_Z51, UNCONNECTED_HIER_Z52,
       UNCONNECTED_HIER_Z53, UNCONNECTED_HIER_Z54;
  wire UNCONNECTED_HIER_Z55, UNCONNECTED_HIER_Z56,
       UNCONNECTED_HIER_Z57, UNCONNECTED_HIER_Z58,
       UNCONNECTED_HIER_Z59, UNCONNECTED_HIER_Z60,
       UNCONNECTED_HIER_Z61, UNCONNECTED_HIER_Z62;
  wire UNCONNECTED_HIER_Z63, UNCONNECTED_HIER_Z64,
       UNCONNECTED_HIER_Z65, UNCONNECTED_HIER_Z66,
       UNCONNECTED_HIER_Z67, UNCONNECTED_HIER_Z68,
       UNCONNECTED_HIER_Z69, UNCONNECTED_HIER_Z70;
  wire UNCONNECTED_HIER_Z71, UNCONNECTED_HIER_Z72,
       UNCONNECTED_HIER_Z73, UNCONNECTED_HIER_Z74, n_0, n_1, n_2, n_3;
  wire n_4, n_5;
  ArbiterPUF_Chain puf1(Trigger, {UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7}, puf_bits[0]);
  ComplexPUF_Chain puf2(Trigger, {UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15}, UNCONNECTED_HIER_Z23, puf_bits[1]);
  ArbiterPUF_Chain_15 puf3(Trigger, {UNCONNECTED_HIER_Z31,
       UNCONNECTED_HIER_Z30, UNCONNECTED_HIER_Z29,
       UNCONNECTED_HIER_Z28, UNCONNECTED_HIER_Z27,
       UNCONNECTED_HIER_Z26, UNCONNECTED_HIER_Z25,
       UNCONNECTED_HIER_Z24}, puf_bits[2]);
  ComplexPUF_Chain_3_17 puf4(Trigger, {UNCONNECTED_HIER_Z39,
       UNCONNECTED_HIER_Z38, UNCONNECTED_HIER_Z37,
       UNCONNECTED_HIER_Z36, UNCONNECTED_HIER_Z35,
       UNCONNECTED_HIER_Z34, UNCONNECTED_HIER_Z33,
       UNCONNECTED_HIER_Z32}, UNCONNECTED_HIER_Z40, puf_bits[3]);
  ArbiterPUF_Chain_14 puf5(Trigger, {UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z46,
       UNCONNECTED_HIER_Z45, UNCONNECTED_HIER_Z44,
       UNCONNECTED_HIER_Z43, UNCONNECTED_HIER_Z42,
       UNCONNECTED_HIER_Z41}, puf_bits[4]);
  ComplexPUF_Chain_16 puf6(Trigger, {UNCONNECTED_HIER_Z56,
       UNCONNECTED_HIER_Z55, UNCONNECTED_HIER_Z54,
       UNCONNECTED_HIER_Z53, UNCONNECTED_HIER_Z52,
       UNCONNECTED_HIER_Z51, UNCONNECTED_HIER_Z50,
       UNCONNECTED_HIER_Z49}, UNCONNECTED_HIER_Z57, puf_bits[5]);
  ArbiterPUF_Chain_13 puf7(Trigger, {UNCONNECTED_HIER_Z65,
       UNCONNECTED_HIER_Z64, UNCONNECTED_HIER_Z63,
       UNCONNECTED_HIER_Z62, UNCONNECTED_HIER_Z61,
       UNCONNECTED_HIER_Z60, UNCONNECTED_HIER_Z59,
       UNCONNECTED_HIER_Z58}, puf_bits[6]);
  ComplexPUF_Chain_3 puf8(Trigger, {UNCONNECTED_HIER_Z73,
       UNCONNECTED_HIER_Z72, UNCONNECTED_HIER_Z71,
       UNCONNECTED_HIER_Z70, UNCONNECTED_HIER_Z69,
       UNCONNECTED_HIER_Z68, UNCONNECTED_HIER_Z67,
       UNCONNECTED_HIER_Z66}, UNCONNECTED_HIER_Z74, puf_bits[7]);
  xr03d1 g72__2398(.A1 (n_5), .A2 (n_3), .A3 (n_4), .Z (FinalResponse));
  xr03d1 g73__5107(.A1 (n_2), .A2 (puf_bits[2]), .A3 (puf_bits[4]), .Z
       (n_5));
  xr02d1 g74__6260(.A1 (puf_bits[1]), .A2 (puf_bits[6]), .Z (n_4));
  aoim22d1 g75__4319(.A1 (n_0), .A2 (puf_bits[5]), .B1 (n_0), .B2
       (puf_bits[5]), .Z (n_3));
  aoim22d1 g76__8428(.A1 (n_1), .A2 (puf_bits[7]), .B1 (n_1), .B2
       (puf_bits[7]), .Z (n_2));
  inv0d0 g77(.I (puf_bits[0]), .ZN (n_1));
  inv0d0 g78(.I (puf_bits[3]), .ZN (n_0));
endmodule

module XOR_PUF_Top(trigger, challenge, response);
  input trigger;
  input [7:0] challenge;
  output response;
  wire trigger;
  wire [7:0] challenge;
  wire response;
  wire UNCONNECTED_HIER_Z75, UNCONNECTED_HIER_Z76,
       UNCONNECTED_HIER_Z77, UNCONNECTED_HIER_Z78,
       UNCONNECTED_HIER_Z79, UNCONNECTED_HIER_Z80,
       UNCONNECTED_HIER_Z81, UNCONNECTED_HIER_Z82;
  XOR_PUF puf_inst(.Trigger (trigger), .Challenge
       ({UNCONNECTED_HIER_Z82, UNCONNECTED_HIER_Z81,
       UNCONNECTED_HIER_Z80, UNCONNECTED_HIER_Z79,
       UNCONNECTED_HIER_Z78, UNCONNECTED_HIER_Z77,
       UNCONNECTED_HIER_Z76, UNCONNECTED_HIER_Z75}), .FinalResponse
       (response));
endmodule

module XOR_PUF_Top_With_Pads(i_trigger_pad, i_challenge_pad,
     o_response_pad);
  input i_trigger_pad;
  input [7:0] i_challenge_pad;
  output o_response_pad;
  wire i_trigger_pad;
  wire [7:0] i_challenge_pad;
  wire o_response_pad;
  wire UNCONNECTED_HIER_Z83, UNCONNECTED_HIER_Z84,
       UNCONNECTED_HIER_Z85, UNCONNECTED_HIER_Z86,
       UNCONNECTED_HIER_Z87, UNCONNECTED_HIER_Z88,
       UNCONNECTED_HIER_Z89, UNCONNECTED_HIER_Z90;
  wire response_int, trigger_int;
  XOR_PUF_Top core(.trigger (trigger_int), .challenge
       ({UNCONNECTED_HIER_Z90, UNCONNECTED_HIER_Z89,
       UNCONNECTED_HIER_Z88, UNCONNECTED_HIER_Z87,
       UNCONNECTED_HIER_Z86, UNCONNECTED_HIER_Z85,
       UNCONNECTED_HIER_Z84, UNCONNECTED_HIER_Z83}), .response
       (response_int));
  pc3o05 pad_resp(.I (response_int), .PAD (o_response_pad));
  pc3d01 pad_trigger(.PAD (i_trigger_pad), .CIN (trigger_int));
endmodule

